#!/usr/bin/env python

def options(opt):
    opt.load('gcc compiler_c compiler_cxx')

def configure(cfg):
    cfg.env.CFLAGS = ['-O3', '-Wall']
    cfg.load('gcc compiler_c compiler_cxx')

def build(bld):
    bld(features='cxx cxxprogram',
        source=bld.path.ant_glob('Beagle_DHT22.cc Beagle_GPIO.cc'),
        lib=['rt'],
        target='dht22')

